name: classmate
description: A Planner App. for School, Work and Home.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    animated_text_kit: ^4.1.1
    bloc_test: ^8.0.0
    connectivity_plus: ^1.0.0
    cupertino_icons: ^1.0.2
    equatable: ^2.0.0
    flutter_bloc: ^7.0.0
    flutter_launcher_icons: ^0.9.0
    flutter_native_splash: ^1.1.7+1
    google_fonts: ^2.0.0
    hydrated_bloc: ^7.0.0
    logger: ^1.0.0
    path_provider: ^2.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/images/logo/
        - google_fonts/
    fonts:
        - family: Averta
          fonts:
              - asset: assets/custom_fonts/Averta/AvertaDemoPE-Regular.ttf
              - asset: assets/custom_fonts/Averta/AvertaDemoPE-ExtraboldItalic.ttf
                weight: 800

flutter_native_splash:
    # Install using: flutter pub run flutter_native_splash:create
    # To restore defaults: flutter pub run flutter_native_splash:remove
    # Only one parameter can be used, color and background_image cannot both be set.
    color: '#ffffff'
    image: assets/images/logo/black_plain.png
    #background_image: "assets/background.png"
    color_dark: '#000000'
    image_dark: assets/images/logo/white_plain.png
    #background_image_dark: "assets/dark-background.png"

flutter_icons:
    # Install using: flutter pub run flutter_launcher_icons:main
    adaptive_icon_foreground: assets/images/logo/black_plain.png
    image_path: assets/images/logo/black_plain.png
    adaptive_icon_background: '#000000'
    android: true
    ios: true
