name: classmate
description: A Planner App. for School, Work and Home.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.1.1
  another_flushbar: ^1.10.20
  cloud_firestore: ^1.0.4
  cupertino_icons: ^1.0.2
  cupertino_radio_choice: ^1.0.1+1
  date_picker_timeline: ^1.2.3
  equatable: ^2.0.0
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  flutter_bloc: ^7.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_snake_navigationbar: ^0.5.0
  flutter_speed_dial: ^3.0.5
  future_button: ^0.1.2
  google_fonts: ^2.0.0
  intl: ^0.17.0
  logger: ^1.0.0
  meta: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  rounded_loading_button: ^1.0.18
  sailor: ^0.7.1
  string_validator: ^0.3.0
  sweetsheet: ^0.3.1
  table_calendar: ^3.0.0
  toggle_switch: ^0.1.9
  video_player: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/videos/
    - google_fonts/
    - assets/gifs/
  fonts:
    - family: Averta
      fonts:
        - asset: assets/custom_fonts/Averta/AvertaDemoPE-Regular.ttf
        - asset: assets/custom_fonts/Averta/AvertaDemoPE-ExtraboldItalic.ttf
          weight: 800
    - family: Akrobat
      fonts:
        - asset: assets/custom_fonts/Akrobat/Akrobat-Thin.otf
          weight: 100
        - asset: assets/custom_fonts/Akrobat/Akrobat-ExtraLight.otf
          weight: 200
        - asset: assets/custom_fonts/Akrobat/Akrobat-Regular.otf
          weight: 400
        - asset: assets/custom_fonts/Akrobat/Akrobat-Bold.otf
          weight: 500
        - asset: assets/custom_fonts/Akrobat/Akrobat-SemiBold.otf
          weight: 600
        - asset: assets/custom_fonts/Akrobat/Akrobat-ExtraBold.otf
          weight: 800
        - asset: assets/custom_fonts/Akrobat/Akrobat-Black.otf
          weight: 900

# Native Splash Screen When Opening The App
flutter_native_splash:
  # Install using: flutter pub run flutter_native_splash:create
  # To restore defaults: flutter pub run flutter_native_splash:remove
  # Only one parameter can be used, color and background_image cannot both be set.
  color: '#ffffff'
  image: assets/images/logo/black_500px.png
  #background_image: "assets/background.png"
  color_dark: '#000000'
  image_dark: assets/images/logo/white_500px.png
  #background_image_dark: "assets/dark-background.png"

flutter_icons:
  # Install using: flutter pub run flutter_launcher_icons:main
  image_path: assets/images/logo/sample_b.png
  remove_alpha_ios: true
  android: true
  ios: true
